### ISSUE TITLE
Looking to add a quick image command! :D

### ISSUE THREAD

**Issue by Dahduh** [Gravestorm/Gravebot#58]
Hey friendos, 

My buds and I on our server were hoping to have a command to end arguments, something like !endall linking to the attached image. Think we could get that? 

Much love!

![endall](https://cloud.githubusercontent.com/assets/16602786/12188403/ffea8386-b582-11e5-93e7-f32bba51e756.png)

**Comment by Gravestorm** [comment]
You can now safely end all arguments with Gravebot, enjoy. :smiley: 

!endall
