### ISSUE TITLE
Command Suggestions

### ISSUE THREAD

**Issue by Teleclast** [Gravestorm/Gravebot#59]
Invite people to play game
Start a vote with [topic]
Search anime/manga [MyAnimeList or AniList] provide info for anime/link to it when queried.
Do the same for video games.
Provide weather by zipcode or City,State
Prune X - Prune last X messages
Prune @user X - Prune last X messages from @user
Cleverbot - In the vain of meme commands, might as well let it message cleverbot
Reddit search - Let it search reddit, or a specific subreddit and reply with search link and best hit
!dictionary - Like urban dictionary but for dictionary.com
Catpost - Random catpost
rule34 - Searches rule34
e621 - Same but for e621
paheal - Same but for paheal
deviantart - Allow users to store and share deviantArt account (Store yours by ID, let others use deviantArt <name> to get your link)
Marquee text
whowas/whois - Similar to IRC but with the relevant info obtainable from Discord
Bait - Random 'bait' image as response

There's a lot of room for specific game related bots, as I'm sure you're aware with the LoL implementation but I think unless you use modules of some sort that will get heavy too fast.

**Comment by dustinblackman** [comment]
Thanks for the suggestions! 

I'm not afraid of things getting heavy fast. The repo is properly setup to handle multiple integrations of whatever we want. I'm going to take some time tomorrow go through all of these with @Gravestorm and makes individual issues for them so they're easier to track. Thanks again!
