### ISSUE TITLE
Cat API

### ISSUE THREAD

**Issue by dustinblackman** [Gravestorm/Gravebot#62]
http://thecatapi.com/

**Comment by PhunStyle** [comment]
Did something similar from randomcat but the API is very basic and can only produce one random cat picture.

```
import Promise from 'bluebird';
import _request from 'request';
import R from 'ramda';

import sentry from './config/sentry';

const request = Promise.promisify(_request);

function randomcat(bot, msg) {
  let options = {
    url: `http://random.cat/meow.php`,
    json: true
  };

  request(options)
    .then(R.path(['body', 'file']))
    .then(text => bot.sendMessage(msg.channel, text))
    .catch(err => {
      sentry.captureError(err);
      bot.sendMessage(msg.channel, `Error: ${err.message}`);
    });
}

export default {
  randomcat: randomcat
};
```

**Comment by dustinblackman** [comment]
Looks great, thanks! Why not throw it up in a PR that way you get credit in the repo? :)

**Comment by PhunStyle** [comment]
Hi dustin! I'm quite new to coding, especially to node, npm and the sorts so i don't really have that much experience. I would've written a test with it if the pugbomb script had one i could use as a cheat sheet.

This is why i decided to post the js file here.
